### ISSUE TITLE
Instruction for reproducing the submission is lacking

### ISSUE THREAD

**Issue by weihua916** [xfcui/CoAtGIN#1]

**Comment by xfcui** [comment]
Do you mean this?

https://github.com/xfcui/CoAtGIN/tree/main/model.tiny

**Comment by weihua916** [comment]
Yes, I saw that. I am confused because you had multiple CoAtGIN submissions, and they all point to this repo? It is unclear to me which command one should one use to reproduce each.

**Comment by xfcui** [comment]
I believe OGB used to keep only the most recent submission for each team. Recently, we noticed that multiple submissions are allowed for the same team. One of my student also reported this issue as a bug to OGB via email. However, the replied email claimed that multiple submissions are allowed.
 
I do believe mainining one repo for each team is more convinient for not only OGB and us, but also for potentail users of our software. I also dought any team is curretnly maintaining one repo for each submission. I would be more than happy to delete our older submissions and keep only the newest one.

**Comment by weihua916** [comment]
Yes, multiple submissions per team are allowed. Ideally, you can explicitly mention in your repository that this repo is for reproducing your newest entry submitted at month/day/year. Let me know once this is done.

**Comment by xfcui** [comment]
Yeah, the date has been added.

BTW, this work has been published on IEEE BIBM 2022. In order to avoid confusions, I will create a new repo instead of working on the same one.
